### ISSUE TITLE
Publish 3.1.13 (and 4.0) to npm?

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-mousewheel#142]
Only @brandonaaron and @substack have npm owner on this repo, if one of  you could add me as an owner I will take care of the publishing.

There are several branches here that are not published, @brandonaaron what are your thoughts on 4.0? Would it be worth trying to clean that up and publish? It appears people are managing to find it, see #141.

**Comment by brandonaaron** [comment]
Added you as an owner.

The 4.0 branch has some neat ideas, cleans up a bit, and actually adds real unit tests. I think I should have named it "experimental" or something like that instead of 4.0. I think it'd be useful for someone to continue that work. I'm not sure if all the settings features are necessary but it is an interesting approach to make this event based plugin configurable per-target.

**Comment by dmethvin** [comment]
Closing for #145 which has a bit more focus.
