### ISSUE TITLE
Scroll direction is opposite than default behavior

### ISSUE THREAD

**Issue by elinake** [jquery/jquery-mousewheel#178]
In default scrolling "down" is negative number and up is a positive number. In this plugin it is exactly the opposite. Basically what you do, is to multiply delta in code by -1, and then do the same again in your scroll.html -test at line 38. Why?

**Comment by mgol** [comment]
The plugin emulates the non-standard `mousewheel` event which has the opposite sign than the standard `wheel` one: https://jsfiddle.net/bhjcgrcu/1/. There are plans to change that in the next major version of the plugin but it's not set in stone yet.

If you have a more concrete issue, please add a test case on https://jsfiddle.net so that it's clear what you expect to be different.
