### ISSUE TITLE
Jump to last screen

### ISSUE THREAD

**Issue by crashbdx** [jquery/jquery-mousewheel#193]
If i mouse wheel faster than 1 by 1 mouse increment in loop:true it always go to last slide before starting moving right or left, is it known issue ? is there any fix for that ?

```
        owl.on('mousewheel', function(event) {
            console.log(event.deltaX, event.deltaY, event.deltaFactor);
        });
```

Give me ether : -0 1 100 or -0 -1 100 all the time, issue on every browser, chrome, Firefox, Edge

**Comment by mgol** [comment]
I'm not sure what you mean by slides as there's no such concept in jQuery Mousewheel itself; I assume you're using it in tandem with some other plugin?

Most likely you have a mouse + OS configuration that doesn't support smooth scroll so you always get a large number there, unlike what you'd get on macOS. This needs to be handled by the code that uses the Mousewheel plugin.

I don't see anything actionable for us here so I'll close the issue. If you provide further details and it turns out there's something to improve in this repository, we'll reopen.

Thanks!
